### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by dconnolly** [zcash/orchard#39]
There is a test that seems to fail consistently while changes are merged, and the clippy checks are ignored. If the clippy checks are informational only, the status code of the checks can be changed to report the clippy output as annotations while registering as a green check.

**Comment by str4d** [comment]
The test that fails constantly is the benchmark runner, because we have no benchmarks yet. Now that we have the key components implemented, I could silence that by adding a small key derivation benchmark.

Re: clippy checks, I want all the "unused Foo" checks to be informational for now (since they will continue to be unused until we get the rest of the protocol implemented), but everything else to be an error. Is there a way to configure clippy like this?
